language: java

sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/.m2
    - $HOME/.cache

before_install:
  - docker pull akvo/flow-maven-build

script:
  - ./docker/bootstrap-build.sh
