language: java

sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/.m2
    - $HOME/.cache
    - $HOME/google-cloud-sdk

before_install:
  - docker pull akvo/flow-maven-build
  - if [[ ! -f "$HOME/google-cloud-sdk/bin/gcloud" ]]; then rm -rf "$HOME/google-cloud-sdk";
    curl https://sdk.cloud.google.com | bash > /dev/null; fi
  - pip install pyopenssl

script:
  - "./ci/bootstrap-build.sh /app/src/ci/build.sh && ./ci/deploy.sh"

before_cache:
 - find $HOME/.m2 -name resolver-status.properties -exec rm {} \;

env:
  global:
  - PATH=$HOME/google-cloud-sdk/bin:$PATH
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - CLOUDSDK_PYTHON_SITEPACKAGES=1
