language: java

sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/.m2
    - $HOME/.cache

before_install:
  - docker pull akvo/flow-maven-build
  - docker pull google/cloud-sdk:latest

script:
  - "./ci/bootstrap-build.sh /app/src/ci/build.sh && ./ci/deploy.sh"
