version: "3"
services:
  akvo-flow:
    build: .
    network_mode: "host"
    entrypoint: /app/src/ci/setup-dev-user-in-container.sh
    command: /app/src/ci/devserver.sh
    working_dir: /app/src
    volumes:
     - .:/app/src/:delegated
     - ~/.m2:/root/.m2:delegated
     - ~/.m2:/home/akvo/.m2:delegated
